# Generated by Django 5.0.6 on 2024-05-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_user_email_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_type', models.CharField(choices=[('maincourse', 'Main Course'), ('dessert', 'Dessert'), ('appetizer', 'Appetizer')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
