# Generated by Django 4.2.13 on 2024-05-23 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
