# Generated by Django 4.2.13 on 2024-05-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_user_withoutusername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_withoutusername',
        ),
    ]
